language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
script:
  - protocol/selfTest.sh
  - cargo build --verbose
  - cargo test --verbose
after_script:
  - bash <(curl -s https://codecov.io/bash)
